/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { CalendarFindManyArgs } from "../../calendar/base/CalendarFindManyArgs";
import { Calendar } from "../../calendar/base/Calendar";
import { CalendarWhereUniqueInput } from "../../calendar/base/CalendarWhereUniqueInput";
import { TimeEntryFindManyArgs } from "../../timeEntry/base/TimeEntryFindManyArgs";
import { TimeEntry } from "../../timeEntry/base/TimeEntry";
import { TimeEntryWhereUniqueInput } from "../../timeEntry/base/TimeEntryWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/calendars")
  @ApiNestedQuery(CalendarFindManyArgs)
  async findCalendars(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Calendar[]> {
    const query = plainToClass(CalendarFindManyArgs, request.query);
    const results = await this.service.findCalendars(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/calendars")
  async connectCalendars(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/calendars")
  async updateCalendars(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/calendars")
  async disconnectCalendars(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/timeEntries")
  @ApiNestedQuery(TimeEntryFindManyArgs)
  async findTimeEntries(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TimeEntry[]> {
    const query = plainToClass(TimeEntryFindManyArgs, request.query);
    const results = await this.service.findTimeEntries(params.id, {
      ...query,
      select: {
        calendar: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        description: true,

        entryType: {
          select: {
            id: true,
          },
        },

        hoursWorked: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/timeEntries")
  async connectTimeEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TimeEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeEntries: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/timeEntries")
  async updateTimeEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TimeEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeEntries: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/timeEntries")
  async disconnectTimeEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TimeEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timeEntries: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
