/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TimeEntry } from "./TimeEntry";
import { TimeEntryCountArgs } from "./TimeEntryCountArgs";
import { TimeEntryFindManyArgs } from "./TimeEntryFindManyArgs";
import { TimeEntryFindUniqueArgs } from "./TimeEntryFindUniqueArgs";
import { CreateTimeEntryArgs } from "./CreateTimeEntryArgs";
import { UpdateTimeEntryArgs } from "./UpdateTimeEntryArgs";
import { DeleteTimeEntryArgs } from "./DeleteTimeEntryArgs";
import { Calendar } from "../../calendar/base/Calendar";
import { EntryType } from "../../entryType/base/EntryType";
import { User } from "../../user/base/User";
import { TimeEntryService } from "../timeEntry.service";
@graphql.Resolver(() => TimeEntry)
export class TimeEntryResolverBase {
  constructor(protected readonly service: TimeEntryService) {}

  async _timeEntriesMeta(
    @graphql.Args() args: TimeEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TimeEntry])
  async timeEntries(
    @graphql.Args() args: TimeEntryFindManyArgs
  ): Promise<TimeEntry[]> {
    return this.service.timeEntries(args);
  }

  @graphql.Query(() => TimeEntry, { nullable: true })
  async timeEntry(
    @graphql.Args() args: TimeEntryFindUniqueArgs
  ): Promise<TimeEntry | null> {
    const result = await this.service.timeEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TimeEntry)
  async createTimeEntry(
    @graphql.Args() args: CreateTimeEntryArgs
  ): Promise<TimeEntry> {
    return await this.service.createTimeEntry({
      ...args,
      data: {
        ...args.data,

        calendar: args.data.calendar
          ? {
              connect: args.data.calendar,
            }
          : undefined,

        entryType: args.data.entryType
          ? {
              connect: args.data.entryType,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TimeEntry)
  async updateTimeEntry(
    @graphql.Args() args: UpdateTimeEntryArgs
  ): Promise<TimeEntry | null> {
    try {
      return await this.service.updateTimeEntry({
        ...args,
        data: {
          ...args.data,

          calendar: args.data.calendar
            ? {
                connect: args.data.calendar,
              }
            : undefined,

          entryType: args.data.entryType
            ? {
                connect: args.data.entryType,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TimeEntry)
  async deleteTimeEntry(
    @graphql.Args() args: DeleteTimeEntryArgs
  ): Promise<TimeEntry | null> {
    try {
      return await this.service.deleteTimeEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Calendar, {
    nullable: true,
    name: "calendar",
  })
  async getCalendar(
    @graphql.Parent() parent: TimeEntry
  ): Promise<Calendar | null> {
    const result = await this.service.getCalendar(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => EntryType, {
    nullable: true,
    name: "entryType",
  })
  async getEntryType(
    @graphql.Parent() parent: TimeEntry
  ): Promise<EntryType | null> {
    const result = await this.service.getEntryType(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: TimeEntry): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
